### PR TITLE
issue #606: replace play-json with circe in results module and refactor result models

### PR DESCRIPTION
**Pull request by zy4**

### CODE REVIEW

**Comment by vikramalva** [comment]
Since this needs thorough testing and I am busy with other things presently, I would wait with the merge.

**Comment by vikramalva** [comment]
All Alignment sections tools are broken - after a job runs through, the Results page is not displayed.

**Comment by zy4** [comment]
/cc @vikramalva 

I fixed a bunch of bugs. Could you take another look? 
I couldn't test so far:

* BLAST
* Hmmer

due to the fact that the cluster has been full over the course of the last weekend.

**Comment by zy4** [comment]
/cc @vikramalva 

please check again.
I recommend to merge it into develop. There are still code quality improvements to make. I want to postpone them because getting the vue frontend working has higher priority.

**Pull request merged**
