### PR TITLE
refactor file watcher

### PR DESCRIPTION
**Pull request by zy4**
- remove usage of `var`
- initialize file watcher in module binding eagerly
- use more functional syntax

### CODE REVIEW

**Comment by felixgabler** [comment]
This does not refresh the `values` in tools conf, does it?

**Comment by zy4** [comment]
No, I changed it (`values`) from `var` to `def`. It will be the latest version in any case or is it important to memoize it? If so, I can add that as well.

**Comment by felixgabler** [comment]
I don't know how this would affect performance. We already cache on the level of the GenerativeParamFiles, so it could be fine. But given that every page open loads this multiple times, it would be good to optimize it.

**Comment by zy4** [comment]
Now it is cached by an atomic reference which only gets updated when needed (create or update event on that specific file)

**Comment by felixgabler** [comment]
Looks good to me

**Review by felixgabler — APPROVED** [review]

**Comment by vikramalva** [comment]
> Now it is cached by an atomic reference which only gets updated when needed (create or update event on that specific file)
> 
> @vikramalva, please test

@zy4 The compilation is stuck here:
image

The develop branch compiles normally. sbt clean && sbt cleanFiles did not help.

**Comment by zy4** [comment]
Hmm, looks like a Mongo issue and rather unrelated. Can you try it on a different branch?

**Comment by vikramalva** [comment]
> Hmm, looks like a Mongo issue and rather unrelated. Can you try it on a different branch?

We always get that mongo warning. Other branches work normally. When I switch from a running instance of the develop branch refactor in place, I get the following errors:

target/scala-2.13/classes ...
[error] /ebio/abt1_share/toolkit_support1/vikram/PROTEINEVOLUTION/Toolkit/modules/tools/src/main/scala/de/proteinevolution/tools/ConfigWatcher.scala:21:8: not found: object fs2
[error] import fs2.Stream
[error]        ^
[error] /ebio/abt1_share/toolkit_support1/vikram/PROTEINEVOLUTION/Toolkit/modules/tools/src/main/scala/de/proteinevolution/tools/ConfigWatcher.scala:23:8: not found: object fs2
[error] import fs2.io.file.Files
[error]        ^
[error] /ebio/abt1_share/toolkit_support1/vikram/PROTEINEVOLUTION/Toolkit/modules/tools/src/main/scala/de/proteinevolution/tools/ConfigWatcher.scala:25:8: not found: object fs2
[error] import fs2.io.Watcher
[error]        ^

**Review by felixgabler — APPROVED** [review]
Did you change the scalafmt config? It formats code differently than my scalafmt.

**Comment by zy4** [comment]
Yeah, looks strange that the diff is in accordance with our linting rules. But I think it looks prettier now.
I used the newest version of IntelliJ.
When I execute `sbt scalafmt` on the command line, it stays like that. I think there are still many rules undefined.

**Comment by felixgabler** [comment]
I have the feeling that scalafmt does not format the code in the modules folders. Do you know anything about this? If you change code inside of app, e.g. MainRouter, it will be formatted correctly, no?

**Comment by zy4** [comment]
I will update / fix scalafmt in a separate PR soon

**Review by vikramalva — APPROVED** [review]

**Pull request merged**
